services:
  qdrant:
    image: qdrant/qdrant:v1.13.0
    container_name: qdrant
    restart: always
    ports:
      - "6333:6333"  # HTTP API
      - "6334:6334"  # gRPC API (el que usa Spring AI)
    volumes:
      - ./qdrant_storage:/qdrant/storage